services:
  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command:
      - "-config.file=/etc/tempo.yaml"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - 3200 # http
      - 9095 # grpc
      - 4417 # otlp grpc
      - 4418 # otlp http
